sealedSecrets:
  release-secret:
    encryptedData:
      API_KEY: dmVyeS1zZWNyZXQtZW52MDEyMzQ1Njc4OQ==
    template:
      metadata:
        labels:
          app.kubernetes.io/name: "{{ .Release.Name }}"
        annotations:
          deployment-namespace: "{{ .Release.Namespace }}"
