sealedSecrets:
  first-secret:
    encryptedData:
      ENV_VAR_ONE: dmVyeS1zZWNyZXQtZW52MDEyMzQ1Njc4OQ==

  second-secret:
    encryptedData:
      ENV_VAR_TWO: dmVyeS1zZWNyZXQtZW52MDEyMzQ1Njc4OQ==
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: app-two
          team: platform
        annotations:
          app.kubernetes.io/managed-by: "sealed-secrets"
          config.kubernetes.io/version: "1"

  third-secret:
    encryptedData:
      tls.crt: dmVyeS1zZWNyZXQtdGxzLWNydDAxMjM0NTY3ODk=
      tls.key: dmVyeS1zZWNyZXQtdGxzLWtleTAxMjM0NTY3ODk=
    template:
      type: kubernetes.io/tls

  fourth-secret:
    encryptedData:
      password: dmVyeS1zZWNyZXQtZW52MDEyMzQ1Njc4OQ==
    template:
      data:
        conn_string: "postgresql://user:{{ .password }}@localhost/mydatabase"

  fifth-secret:
    encryptedData:
      ENV_VAR_FIVE: dmVyeS1zZWNyZXQtZW52MDEyMzQ1Njc4OQ==
    metadata:
      name: custom-secret-name
      namespace: custom-namespace
