{{- range $name, $resource := .Values.resources }}
{{- if ne ($resource.enabled) false }}
{{- $resource := deepCopy $resource }}
{{- $_ := unset $resource "enabled" }}
{{- $metadata := (default dict $resource.metadata) }}
{{- $metadata := (include "templates.metadata" (dict "root" $ "metadata" $metadata "name" $name) | fromYaml) }}
{{- $_ := set $resource "metadata" $metadata }}
---
{{ tpl (toYaml $resource) $ }}
{{- end }}
{{- end }}
