{{- range $name, $value := .Values.sealedSecrets }}
{{- if not $value.encryptedData }}
  {{- fail (printf "sealedSecrets.%s.encryptedData is required" $name) }}
{{- end }}

{{- $metadata := (default dict $value.template).metadata | default dict }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  encryptedData:
  {{- range $key, $secret := $value.encryptedData }}
    {{ $key }}: {{ $secret | quote }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        {{- with $metadata.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $metadata.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    type: {{ (default dict $value.template).type | default "Opaque" | quote }}
    {{- with (default dict $value.template).data }}
    data:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
