{{- range $name, $value := .Values.sealedSecrets }}
{{- if and $value (ne $value.enabled false) }}
{{- if not $value.encryptedData }}
  {{- fail (printf "sealedSecrets.%s.encryptedData is required" $name) }}
{{- end }}

{{- $templateMetadata := (default dict $value.template).metadata | default dict }}
{{- $metadata := (include "common.metadata" (dict "root" $ "metadata" (default dict $value.metadata) "name" $name) | fromYaml) }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $metadata.name | quote }}
  namespace: {{ $metadata.namespace | quote }}
  labels:
    {{- toYaml $metadata.labels | nindent 4 }}
  {{- with $metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
  {{- range $key, $secret := $value.encryptedData }}
    {{ $key }}: {{ $secret | quote }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" $ | nindent 8 }}
        {{- with $templateMetadata.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $templateMetadata.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    type: {{ (default dict $value.template).type | default "Opaque" | quote }}
    {{- with (default dict $value.template).data }}
    data:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
