{{- range $name, $value := .Values.traefikMiddlewares }}
{{- if not (hasKey $value "spec") }}
  {{- fail (printf "traefikMiddlewares.%s.spec is required" $name) }}
{{- end }}

{{- $metadata := (include "common.metadata" (dict "root" $ "metadata" (default dict $value.metadata) "name" $name) | fromYaml) }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $metadata.name | quote }}
  namespace: {{ $metadata.namespace | quote }}
  labels:
    {{- toYaml $metadata.labels | nindent 4 }}
  {{- with $metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $value.spec | nindent 2 }}
{{- end }}
