# -- Map of SealedSecret resources to render.
# Each top-level key becomes the SealedSecret name.
sealedSecrets: {}

# -- Map of Kubernetes NetworkPolicy resources to render.
networkPolicies: {}

# -- Map of CiliumNetworkPolicy resources to render.
ciliumNetworkPolicies: {}

# -- Map of Traefik Middleware resources to render.
traefikMiddlewares: {}

# -- Map of Kubernetes resources to render as-is.
# Each key becomes the default metadata.name if not provided.
resources: {}
